apiVersion: v1
kind: Pod
metadata:
  name: archlinux
  labels:
    app: archapp
spec:
  containers:
  - image: archlinux:latest
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: archl
  restartPolicy: Always