apiVersion: v1
kind: Pod
metadata:
  name: app1
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: sampl7
    image: httpd
    volumeMounts:
    - name: html
      mountPath: /var/www/html/
  - name: os7
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done